package controllers

import models.AirlineAircraft
import persistence.Serializer

/**
 * Controller class for managing the relationship between airlines and their aircraft.
 * Provides functionality to add, update, delete, list, and persist airline fleets.
 *
 * @property serializer The serializer used for saving and loading airline-aircraft data.
 */
class AirlineAircraftController(serializerType: Serializer) {
    private var airlineAircraft = mutableListOf<AirlineAircraft>()
    private var serializer: Serializer = serializerType

    /**
     * Loads airline-aircraft data from the serializer into memory.
     *
     * @throws Exception if loading fails.
     */
    @Throws
    fun load() {
        airlineAircraft = serializer.read() as MutableList<AirlineAircraft>
    }

    /**
     * Stores the current airline-aircraft list to the serializer.
     *
     * @throws Exception if storing fails.
     */
    @Throws
    fun store() {
        serializer.write(airlineAircraft)
    }

    /**
     * Adds a new aircraft to an airline's fleet.
     *
     * @param airlineId The ID of the airline.
     * @param aircraftId The ID of the aircraft.
     * @param registration The registration code of the aircraft.
     * @param yearBought The year the aircraft was purchased.
     * @param hoursFlown Total hours flown by the aircraft.
     * @param revenuePerYear Annual revenue generated by the aircraft (in millions).
     * @param isRetired Indicates if the aircraft is retired.
     */
    fun addAircraftToAirline(
        airlineId: Int,
        aircraftId: Int,
        registration: String,
        yearBought: Int,
        hoursFlown: Int,
        revenuePerYear: Double,
        isRetired: Boolean,
    ) {
        airlineAircraft.add(AirlineAircraft(airlineId, aircraftId, registration, yearBought, hoursFlown, revenuePerYear, isRetired))
    }

    /**
     * Updates details of an aircraft in an airline's fleet.
     *
     * @param airlineId The ID of the airline.
     * @param aircraftId The ID of the aircraft.
     * @param registration The updated registration code.
     * @param yearBought The updated year of purchase.
     * @param hoursFlown The updated total hours flown.
     * @param revenuePerYear The updated annual revenue (in millions).
     * @param isRetired Indicates if the aircraft is retired.
     * @return True if the update was successful, false otherwise.
     */
    fun updateAircraftInAirline(
        airlineId: Int,
        aircraftId: Int,
        registration: String,
        yearBought: Int,
        hoursFlown: Int,
        revenuePerYear: Double,
        isRetired: Boolean,
    ): Boolean {
        val aircraft = airlineAircraft.find { it.airlineId == airlineId && it.aircraftId == aircraftId }
        return if (aircraft != null) {
            aircraft.registration = registration
            aircraft.yearBought = yearBought
            aircraft.hoursFlown = hoursFlown
            aircraft.revenuePerYear = revenuePerYear
            aircraft.isRetired = isRetired
            true
        } else {
            false
        }
    }

    /**
     * Deletes an aircraft from an airline's fleet.
     *
     * @param airlineId The ID of the airline.
     * @param aircraftId The ID of the aircraft.
     * @return The removed AirlineAircraft object if successful, null otherwise.
     */
    fun deleteAircraftInAirline(
        airlineId: Int,
        aircraftId: Int,
    ): AirlineAircraft? {
        val index = airlineAircraft.indexOfFirst { it.airlineId == airlineId && it.aircraftId == aircraftId }
        return if (index != -1) {
            airlineAircraft.removeAt(index)
        } else {
            null
        }
    }

    /**
     * Counts the number of aircraft in a specific airline's fleet.
     *
     * @param airlineId The ID of the airline.
     * @return The number of aircraft in the fleet.
     */
    fun numberOfAircraftInAirline(airlineId: Int): Int {
        return airlineAircraft.count { it.airlineId == airlineId }
    }

    /**
     * Lists all aircraft in a specific airline's fleet.
     *
     * @param airlineId The ID of the airline.
     * @return A formatted string of aircraft details or a message if none found.
     */
    fun listAircraftInAirline(airlineId: Int): String {
        val fleet = airlineAircraft.filter { it.airlineId == airlineId }

        return if (fleet.isEmpty()) {
            "No aircraft found in fleet for Airline ID: ${airlineId}\n"
        } else {
            fleet.joinToString(separator = "") { aircraft ->
                """
                    > ------------------------------------
                    > Airline ID: ${aircraft.airlineId}
                    > Aircraft ID: ${aircraft.aircraftId}
                    > Registration: ${aircraft.registration}
                    > Year Bought: ${aircraft.yearBought}
                    > Hours Flown: ${aircraft.hoursFlown}
                    > Revenue Per Year (in millions): ${aircraft.revenuePerYear}
                    > Retired? ${aircraft.isRetired}
                    > ------------------------------------
                    > 
                """.trimMargin(">")
            }
        }
    }

    /**
     * Finds an aircraft by its registration code.
     *
     * @param registration The registration code to search for.
     * @return The AirlineAircraft object if found, null otherwise.
     */
    fun findAircraftByRegistration(registration: String): AirlineAircraft? {
        return airlineAircraft.find { it.registration == registration }
    }

    /**
     * Retrieves the fleet for a specific airline as a list of AirlineAircraft objects.
     *
     * @param airlineId The ID of the airline.
     * @return A list of AirlineAircraft objects belonging to the airline.
     */
    fun getFleetForAirline(airlineId: Int): List<AirlineAircraft> = airlineAircraft.filter { it.airlineId == airlineId }
}
