package models

/**
 * Represents the relationship between an airline and an aircraft in its fleet,
 * including operational and financial details.
 *
 * @property airlineId The unique identifier of the airline.
 * @property aircraftId The unique identifier of the aircraft.
 * @property registration The registration code of the aircraft.
 * @property yearBought The year the aircraft was purchased by the airline.
 * @property hoursFlown Total flight hours accumulated by the aircraft.
 * @property revenuePerYear Annual revenue generated by the aircraft (in millions).
 * @property isRetired Indicates whether the aircraft is retired from service.
 */
data class AirlineAircraft(
    var airlineId: Int,
    var aircraftId: Int,
    var registration: String,
    var yearBought: Int,
    var hoursFlown: Int,
    var revenuePerYear: Double,
    var isRetired: Boolean,
)
